[[redirects]]
  from = "/api.php?action=query&titles=${finalURL}&prop=pageimages&format=json&pithumbsize=400"
  to = "https://en.wikipedia.org/w/api.php?action=query&titles=${finalURL}&prop=pageimages&format=json&pithumbsize=400"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"